name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_UPDATED_DATE: "False"
          COMMIT_MESSAGE: "Update WakaTime metrics"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TIMEZONE: "False"
          BADGE_STYLE: "social"
  remove-emoji:
    name: Remove emoji from Readme
    needs: update-readme
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: main

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Run Python Script
        run: uv run --with emoji remove_emoji/main.py
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "remove emojis from README [skip ci]"
          file_pattern: "README.md"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
